name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install root dependencies
        run: npm ci
      - name: Install client dependencies
        run: npm ci
        working-directory: client
      - name: Install Playwright dependencies
        run: npm ci
        working-directory: e2e
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: e2e
      - name: Initialise database
        run: npm run init
      - name: Run vitest unit and integration tests
        run: npm run test
      - name: Run Playwright E2E tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30